/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeadLetterRouteImport } from './routes/dead-letter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NewRouteImport } from './routes/new'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as HomeIndexRouteImport } from './routes/_home.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as CredentialsNewRouteImport } from './routes/credentials.new'
import { Route as McpActivityRouteImport } from './routes/mcp.activity'
import { Route as McpCapabilitiesRouteImport } from './routes/mcp.capabilities'
import { Route as McpConnectionRouteImport } from './routes/mcp.connection'
import { Route as McpTokensRouteImport } from './routes/mcp.tokens'
import { Route as OrchestrationOrchestratorsRouteImport } from './routes/orchestration.orchestrators'
import { Route as OrchestrationWorkersRouteImport } from './routes/orchestration.workers'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as SchedulesIdRouteImport } from './routes/schedules.$id'
import { Route as SchedulesNewRouteImport } from './routes/schedules.new'
import { Route as SettingsAccessRouteImport } from './routes/settings.access'
import { Route as TransfersIdRouteImport } from './routes/transfers.$id'
import { Route as TransfersNewRouteImport } from './routes/transfers.new'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as WorkflowsNewRouteImport } from './routes/workflows.new'
import { Route as HomeCIdRouteImport } from './routes/_home.c.$id'
import { Route as AgentsIdActivityRouteImport } from './routes/agents.$id.activity'
import { Route as AgentsIdDestinationsRouteImport } from './routes/agents.$id.destinations'
import { Route as AgentsIdLogsRouteImport } from './routes/agents.$id.logs'
import { Route as AgentsIdOverviewRouteImport } from './routes/agents.$id.overview'
import { Route as AgentsIdRoomsRouteImport } from './routes/agents.$id.rooms'
import { Route as AgentsIdSettingsRouteImport } from './routes/agents.$id.settings'
import { Route as AgentsIdTunnelsRouteImport } from './routes/agents.$id.tunnels'
import { Route as McpTokensNewRouteImport } from './routes/mcp.tokens.new'
import { Route as OrchestrationOrchestratorsIdRouteImport } from './routes/orchestration.orchestrators.$id'
import { Route as OrchestrationWorkersIdRouteImport } from './routes/orchestration.workers.$id'
import { Route as RegistryScopeNameRouteImport } from './routes/registry_.$scope.$name'
import { Route as RoomsIdActivityRouteImport } from './routes/rooms.$id.activity'
import { Route as RoomsIdChannelsRouteImport } from './routes/rooms.$id.channels'
import { Route as RoomsIdMembersRouteImport } from './routes/rooms.$id.members'
import { Route as RoomsIdSettingsRouteImport } from './routes/rooms.$id.settings'
import { Route as RoomsIdTransfersRouteImport } from './routes/rooms.$id.transfers'
import { Route as SchedulesIdEditRouteImport } from './routes/schedules.$id.edit'
import { Route as WorkflowsIdEditorRouteImport } from './routes/workflows.$id.editor'
import { Route as WorkflowsIdOverviewRouteImport } from './routes/workflows.$id.overview'
import { Route as WorkflowsIdRunsRouteImport } from './routes/workflows.$id.runs'
import { Route as WorkflowsIdSettingsRouteImport } from './routes/workflows.$id.settings'
import { Route as WorkflowsRunsIdRouteImport } from './routes/workflows.runs.$id'
import { Route as RoomsIdChannelsChannelIdRouteImport } from './routes/rooms.$id.channels.$channelId'
import { Route as WorkflowsIdRunsRunIdRouteImport } from './routes/workflows.$id.runs.$runId'
import { Route as RoomsIdChannelsChannelIdDetailsRouteImport } from './routes/rooms.$id.channels.$channelId.details'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadLetterRoute = DeadLetterRouteImport.update({
  id: '/dead-letter',
  path: '/dead-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const CredentialsNewRoute = CredentialsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CredentialsRoute,
} as any)
const McpActivityRoute = McpActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => McpRoute,
} as any)
const McpCapabilitiesRoute = McpCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => McpRoute,
} as any)
const McpConnectionRoute = McpConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => McpRoute,
} as any)
const McpTokensRoute = McpTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => McpRoute,
} as any)
const OrchestrationOrchestratorsRoute =
  OrchestrationOrchestratorsRouteImport.update({
    id: '/orchestrators',
    path: '/orchestrators',
    getParentRoute: () => OrchestrationRoute,
  } as any)
const OrchestrationWorkersRoute = OrchestrationWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => OrchestrationRoute,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoomsRoute,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RunsRoute,
} as any)
const SchedulesIdRoute = SchedulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchedulesRoute,
} as any)
const SchedulesNewRoute = SchedulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SchedulesRoute,
} as any)
const SettingsAccessRoute = SettingsAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => SettingsRoute,
} as any)
const TransfersIdRoute = TransfersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransfersRoute,
} as any)
const TransfersNewRoute = TransfersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransfersRoute,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkflowsRoute,
} as any)
const HomeCIdRoute = HomeCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => HomeRoute,
} as any)
const AgentsIdActivityRoute = AgentsIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AgentsIdRoute,
} as any)
const AgentsIdDestinationsRoute = AgentsIdDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AgentsIdRoute,
} as any)
const AgentsIdLogsRoute = AgentsIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AgentsIdRoute,
} as any)
const AgentsIdOverviewRoute = AgentsIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AgentsIdRoute,
} as any)
const AgentsIdRoomsRoute = AgentsIdRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AgentsIdRoute,
} as any)
const AgentsIdSettingsRoute = AgentsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentsIdRoute,
} as any)
const AgentsIdTunnelsRoute = AgentsIdTunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => AgentsIdRoute,
} as any)
const McpTokensNewRoute = McpTokensNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => McpTokensRoute,
} as any)
const OrchestrationOrchestratorsIdRoute =
  OrchestrationOrchestratorsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => OrchestrationOrchestratorsRoute,
  } as any)
const OrchestrationWorkersIdRoute = OrchestrationWorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrchestrationWorkersRoute,
} as any)
const RegistryScopeNameRoute = RegistryScopeNameRouteImport.update({
  id: '/registry_/$scope/$name',
  path: '/registry/$scope/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdActivityRoute = RoomsIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => RoomsIdRoute,
} as any)
const RoomsIdChannelsRoute = RoomsIdChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => RoomsIdRoute,
} as any)
const RoomsIdMembersRoute = RoomsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => RoomsIdRoute,
} as any)
const RoomsIdSettingsRoute = RoomsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RoomsIdRoute,
} as any)
const RoomsIdTransfersRoute = RoomsIdTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => RoomsIdRoute,
} as any)
const SchedulesIdEditRoute = SchedulesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SchedulesIdRoute,
} as any)
const WorkflowsIdEditorRoute = WorkflowsIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => WorkflowsIdRoute,
} as any)
const WorkflowsIdOverviewRoute = WorkflowsIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkflowsIdRoute,
} as any)
const WorkflowsIdRunsRoute = WorkflowsIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => WorkflowsIdRoute,
} as any)
const WorkflowsIdSettingsRoute = WorkflowsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkflowsIdRoute,
} as any)
const WorkflowsRunsIdRoute = WorkflowsRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => WorkflowsRoute,
} as any)
const RoomsIdChannelsChannelIdRoute =
  RoomsIdChannelsChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => RoomsIdChannelsRoute,
  } as any)
const WorkflowsIdRunsRunIdRoute = WorkflowsIdRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => WorkflowsIdRunsRoute,
} as any)
const RoomsIdChannelsChannelIdDetailsRoute =
  RoomsIdChannelsChannelIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => RoomsIdChannelsChannelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/credentials': typeof CredentialsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dead-letter': typeof DeadLetterRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/new': typeof NewRoute
  '/orchestration': typeof OrchestrationRouteWithChildren
  '/queue': typeof QueueRoute
  '/registry': typeof RegistryRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/schedules': typeof SchedulesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/transfers': typeof TransfersRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/credentials/new': typeof CredentialsNewRoute
  '/mcp/activity': typeof McpActivityRoute
  '/mcp/capabilities': typeof McpCapabilitiesRoute
  '/mcp/connection': typeof McpConnectionRoute
  '/mcp/tokens': typeof McpTokensRouteWithChildren
  '/orchestration/orchestrators': typeof OrchestrationOrchestratorsRouteWithChildren
  '/orchestration/workers': typeof OrchestrationWorkersRouteWithChildren
  '/rooms/$id': typeof RoomsIdRouteWithChildren
  '/runs/$id': typeof RunsIdRoute
  '/schedules/$id': typeof SchedulesIdRouteWithChildren
  '/schedules/new': typeof SchedulesNewRoute
  '/settings/access': typeof SettingsAccessRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/workflows/$id': typeof WorkflowsIdRouteWithChildren
  '/workflows/new': typeof WorkflowsNewRoute
  '/c/$id': typeof HomeCIdRoute
  '/agents/$id/activity': typeof AgentsIdActivityRoute
  '/agents/$id/destinations': typeof AgentsIdDestinationsRoute
  '/agents/$id/logs': typeof AgentsIdLogsRoute
  '/agents/$id/overview': typeof AgentsIdOverviewRoute
  '/agents/$id/rooms': typeof AgentsIdRoomsRoute
  '/agents/$id/settings': typeof AgentsIdSettingsRoute
  '/agents/$id/tunnels': typeof AgentsIdTunnelsRoute
  '/mcp/tokens/new': typeof McpTokensNewRoute
  '/orchestration/orchestrators/$id': typeof OrchestrationOrchestratorsIdRoute
  '/orchestration/workers/$id': typeof OrchestrationWorkersIdRoute
  '/registry/$scope/$name': typeof RegistryScopeNameRoute
  '/rooms/$id/activity': typeof RoomsIdActivityRoute
  '/rooms/$id/channels': typeof RoomsIdChannelsRouteWithChildren
  '/rooms/$id/members': typeof RoomsIdMembersRoute
  '/rooms/$id/settings': typeof RoomsIdSettingsRoute
  '/rooms/$id/transfers': typeof RoomsIdTransfersRoute
  '/schedules/$id/edit': typeof SchedulesIdEditRoute
  '/workflows/$id/editor': typeof WorkflowsIdEditorRoute
  '/workflows/$id/overview': typeof WorkflowsIdOverviewRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRouteWithChildren
  '/workflows/$id/settings': typeof WorkflowsIdSettingsRoute
  '/workflows/runs/$id': typeof WorkflowsRunsIdRoute
  '/rooms/$id/channels/$channelId': typeof RoomsIdChannelsChannelIdRouteWithChildren
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
  '/rooms/$id/channels/$channelId/details': typeof RoomsIdChannelsChannelIdDetailsRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/credentials': typeof CredentialsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dead-letter': typeof DeadLetterRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/new': typeof NewRoute
  '/orchestration': typeof OrchestrationRouteWithChildren
  '/queue': typeof QueueRoute
  '/registry': typeof RegistryRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/schedules': typeof SchedulesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/transfers': typeof TransfersRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/credentials/new': typeof CredentialsNewRoute
  '/mcp/activity': typeof McpActivityRoute
  '/mcp/capabilities': typeof McpCapabilitiesRoute
  '/mcp/connection': typeof McpConnectionRoute
  '/mcp/tokens': typeof McpTokensRouteWithChildren
  '/orchestration/orchestrators': typeof OrchestrationOrchestratorsRouteWithChildren
  '/orchestration/workers': typeof OrchestrationWorkersRouteWithChildren
  '/rooms/$id': typeof RoomsIdRouteWithChildren
  '/runs/$id': typeof RunsIdRoute
  '/schedules/$id': typeof SchedulesIdRouteWithChildren
  '/schedules/new': typeof SchedulesNewRoute
  '/settings/access': typeof SettingsAccessRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/workflows/$id': typeof WorkflowsIdRouteWithChildren
  '/workflows/new': typeof WorkflowsNewRoute
  '/': typeof HomeIndexRoute
  '/c/$id': typeof HomeCIdRoute
  '/agents/$id/activity': typeof AgentsIdActivityRoute
  '/agents/$id/destinations': typeof AgentsIdDestinationsRoute
  '/agents/$id/logs': typeof AgentsIdLogsRoute
  '/agents/$id/overview': typeof AgentsIdOverviewRoute
  '/agents/$id/rooms': typeof AgentsIdRoomsRoute
  '/agents/$id/settings': typeof AgentsIdSettingsRoute
  '/agents/$id/tunnels': typeof AgentsIdTunnelsRoute
  '/mcp/tokens/new': typeof McpTokensNewRoute
  '/orchestration/orchestrators/$id': typeof OrchestrationOrchestratorsIdRoute
  '/orchestration/workers/$id': typeof OrchestrationWorkersIdRoute
  '/registry/$scope/$name': typeof RegistryScopeNameRoute
  '/rooms/$id/activity': typeof RoomsIdActivityRoute
  '/rooms/$id/channels': typeof RoomsIdChannelsRouteWithChildren
  '/rooms/$id/members': typeof RoomsIdMembersRoute
  '/rooms/$id/settings': typeof RoomsIdSettingsRoute
  '/rooms/$id/transfers': typeof RoomsIdTransfersRoute
  '/schedules/$id/edit': typeof SchedulesIdEditRoute
  '/workflows/$id/editor': typeof WorkflowsIdEditorRoute
  '/workflows/$id/overview': typeof WorkflowsIdOverviewRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRouteWithChildren
  '/workflows/$id/settings': typeof WorkflowsIdSettingsRoute
  '/workflows/runs/$id': typeof WorkflowsRunsIdRoute
  '/rooms/$id/channels/$channelId': typeof RoomsIdChannelsChannelIdRouteWithChildren
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
  '/rooms/$id/channels/$channelId/details': typeof RoomsIdChannelsChannelIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/credentials': typeof CredentialsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dead-letter': typeof DeadLetterRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/new': typeof NewRoute
  '/orchestration': typeof OrchestrationRouteWithChildren
  '/queue': typeof QueueRoute
  '/registry': typeof RegistryRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/schedules': typeof SchedulesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/transfers': typeof TransfersRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/credentials/new': typeof CredentialsNewRoute
  '/mcp/activity': typeof McpActivityRoute
  '/mcp/capabilities': typeof McpCapabilitiesRoute
  '/mcp/connection': typeof McpConnectionRoute
  '/mcp/tokens': typeof McpTokensRouteWithChildren
  '/orchestration/orchestrators': typeof OrchestrationOrchestratorsRouteWithChildren
  '/orchestration/workers': typeof OrchestrationWorkersRouteWithChildren
  '/rooms/$id': typeof RoomsIdRouteWithChildren
  '/runs/$id': typeof RunsIdRoute
  '/schedules/$id': typeof SchedulesIdRouteWithChildren
  '/schedules/new': typeof SchedulesNewRoute
  '/settings/access': typeof SettingsAccessRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/workflows/$id': typeof WorkflowsIdRouteWithChildren
  '/workflows/new': typeof WorkflowsNewRoute
  '/_home/': typeof HomeIndexRoute
  '/_home/c/$id': typeof HomeCIdRoute
  '/agents/$id/activity': typeof AgentsIdActivityRoute
  '/agents/$id/destinations': typeof AgentsIdDestinationsRoute
  '/agents/$id/logs': typeof AgentsIdLogsRoute
  '/agents/$id/overview': typeof AgentsIdOverviewRoute
  '/agents/$id/rooms': typeof AgentsIdRoomsRoute
  '/agents/$id/settings': typeof AgentsIdSettingsRoute
  '/agents/$id/tunnels': typeof AgentsIdTunnelsRoute
  '/mcp/tokens/new': typeof McpTokensNewRoute
  '/orchestration/orchestrators/$id': typeof OrchestrationOrchestratorsIdRoute
  '/orchestration/workers/$id': typeof OrchestrationWorkersIdRoute
  '/registry_/$scope/$name': typeof RegistryScopeNameRoute
  '/rooms/$id/activity': typeof RoomsIdActivityRoute
  '/rooms/$id/channels': typeof RoomsIdChannelsRouteWithChildren
  '/rooms/$id/members': typeof RoomsIdMembersRoute
  '/rooms/$id/settings': typeof RoomsIdSettingsRoute
  '/rooms/$id/transfers': typeof RoomsIdTransfersRoute
  '/schedules/$id/edit': typeof SchedulesIdEditRoute
  '/workflows/$id/editor': typeof WorkflowsIdEditorRoute
  '/workflows/$id/overview': typeof WorkflowsIdOverviewRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRouteWithChildren
  '/workflows/$id/settings': typeof WorkflowsIdSettingsRoute
  '/workflows/runs/$id': typeof WorkflowsRunsIdRoute
  '/rooms/$id/channels/$channelId': typeof RoomsIdChannelsChannelIdRouteWithChildren
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
  '/rooms/$id/channels/$channelId/details': typeof RoomsIdChannelsChannelIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/auth'
    | '/credentials'
    | '/dashboard'
    | '/dead-letter'
    | '/login'
    | '/mcp'
    | '/new'
    | '/orchestration'
    | '/queue'
    | '/registry'
    | '/rooms'
    | '/runs'
    | '/schedules'
    | '/settings'
    | '/transfers'
    | '/workflows'
    | '/agents/$id'
    | '/agents/new'
    | '/credentials/new'
    | '/mcp/activity'
    | '/mcp/capabilities'
    | '/mcp/connection'
    | '/mcp/tokens'
    | '/orchestration/orchestrators'
    | '/orchestration/workers'
    | '/rooms/$id'
    | '/runs/$id'
    | '/schedules/$id'
    | '/schedules/new'
    | '/settings/access'
    | '/transfers/$id'
    | '/transfers/new'
    | '/workflows/$id'
    | '/workflows/new'
    | '/c/$id'
    | '/agents/$id/activity'
    | '/agents/$id/destinations'
    | '/agents/$id/logs'
    | '/agents/$id/overview'
    | '/agents/$id/rooms'
    | '/agents/$id/settings'
    | '/agents/$id/tunnels'
    | '/mcp/tokens/new'
    | '/orchestration/orchestrators/$id'
    | '/orchestration/workers/$id'
    | '/registry/$scope/$name'
    | '/rooms/$id/activity'
    | '/rooms/$id/channels'
    | '/rooms/$id/members'
    | '/rooms/$id/settings'
    | '/rooms/$id/transfers'
    | '/schedules/$id/edit'
    | '/workflows/$id/editor'
    | '/workflows/$id/overview'
    | '/workflows/$id/runs'
    | '/workflows/$id/settings'
    | '/workflows/runs/$id'
    | '/rooms/$id/channels/$channelId'
    | '/workflows/$id/runs/$runId'
    | '/rooms/$id/channels/$channelId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/auth'
    | '/credentials'
    | '/dashboard'
    | '/dead-letter'
    | '/login'
    | '/mcp'
    | '/new'
    | '/orchestration'
    | '/queue'
    | '/registry'
    | '/rooms'
    | '/runs'
    | '/schedules'
    | '/settings'
    | '/transfers'
    | '/workflows'
    | '/agents/$id'
    | '/agents/new'
    | '/credentials/new'
    | '/mcp/activity'
    | '/mcp/capabilities'
    | '/mcp/connection'
    | '/mcp/tokens'
    | '/orchestration/orchestrators'
    | '/orchestration/workers'
    | '/rooms/$id'
    | '/runs/$id'
    | '/schedules/$id'
    | '/schedules/new'
    | '/settings/access'
    | '/transfers/$id'
    | '/transfers/new'
    | '/workflows/$id'
    | '/workflows/new'
    | '/'
    | '/c/$id'
    | '/agents/$id/activity'
    | '/agents/$id/destinations'
    | '/agents/$id/logs'
    | '/agents/$id/overview'
    | '/agents/$id/rooms'
    | '/agents/$id/settings'
    | '/agents/$id/tunnels'
    | '/mcp/tokens/new'
    | '/orchestration/orchestrators/$id'
    | '/orchestration/workers/$id'
    | '/registry/$scope/$name'
    | '/rooms/$id/activity'
    | '/rooms/$id/channels'
    | '/rooms/$id/members'
    | '/rooms/$id/settings'
    | '/rooms/$id/transfers'
    | '/schedules/$id/edit'
    | '/workflows/$id/editor'
    | '/workflows/$id/overview'
    | '/workflows/$id/runs'
    | '/workflows/$id/settings'
    | '/workflows/runs/$id'
    | '/rooms/$id/channels/$channelId'
    | '/workflows/$id/runs/$runId'
    | '/rooms/$id/channels/$channelId/details'
  id:
    | '__root__'
    | '/_home'
    | '/agents'
    | '/auth'
    | '/credentials'
    | '/dashboard'
    | '/dead-letter'
    | '/login'
    | '/mcp'
    | '/new'
    | '/orchestration'
    | '/queue'
    | '/registry'
    | '/rooms'
    | '/runs'
    | '/schedules'
    | '/settings'
    | '/transfers'
    | '/workflows'
    | '/agents/$id'
    | '/agents/new'
    | '/credentials/new'
    | '/mcp/activity'
    | '/mcp/capabilities'
    | '/mcp/connection'
    | '/mcp/tokens'
    | '/orchestration/orchestrators'
    | '/orchestration/workers'
    | '/rooms/$id'
    | '/runs/$id'
    | '/schedules/$id'
    | '/schedules/new'
    | '/settings/access'
    | '/transfers/$id'
    | '/transfers/new'
    | '/workflows/$id'
    | '/workflows/new'
    | '/_home/'
    | '/_home/c/$id'
    | '/agents/$id/activity'
    | '/agents/$id/destinations'
    | '/agents/$id/logs'
    | '/agents/$id/overview'
    | '/agents/$id/rooms'
    | '/agents/$id/settings'
    | '/agents/$id/tunnels'
    | '/mcp/tokens/new'
    | '/orchestration/orchestrators/$id'
    | '/orchestration/workers/$id'
    | '/registry_/$scope/$name'
    | '/rooms/$id/activity'
    | '/rooms/$id/channels'
    | '/rooms/$id/members'
    | '/rooms/$id/settings'
    | '/rooms/$id/transfers'
    | '/schedules/$id/edit'
    | '/workflows/$id/editor'
    | '/workflows/$id/overview'
    | '/workflows/$id/runs'
    | '/workflows/$id/settings'
    | '/workflows/runs/$id'
    | '/rooms/$id/channels/$channelId'
    | '/workflows/$id/runs/$runId'
    | '/rooms/$id/channels/$channelId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CredentialsRoute: typeof CredentialsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeadLetterRoute: typeof DeadLetterRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRouteWithChildren
  NewRoute: typeof NewRoute
  OrchestrationRoute: typeof OrchestrationRouteWithChildren
  QueueRoute: typeof QueueRoute
  RegistryRoute: typeof RegistryRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  RunsRoute: typeof RunsRouteWithChildren
  SchedulesRoute: typeof SchedulesRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TransfersRoute: typeof TransfersRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  RegistryScopeNameRoute: typeof RegistryScopeNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-letter': {
      id: '/dead-letter'
      path: '/dead-letter'
      fullPath: '/dead-letter'
      preLoaderRoute: typeof DeadLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/credentials/new': {
      id: '/credentials/new'
      path: '/new'
      fullPath: '/credentials/new'
      preLoaderRoute: typeof CredentialsNewRouteImport
      parentRoute: typeof CredentialsRoute
    }
    '/mcp/activity': {
      id: '/mcp/activity'
      path: '/activity'
      fullPath: '/mcp/activity'
      preLoaderRoute: typeof McpActivityRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/capabilities': {
      id: '/mcp/capabilities'
      path: '/capabilities'
      fullPath: '/mcp/capabilities'
      preLoaderRoute: typeof McpCapabilitiesRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/connection': {
      id: '/mcp/connection'
      path: '/connection'
      fullPath: '/mcp/connection'
      preLoaderRoute: typeof McpConnectionRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/tokens': {
      id: '/mcp/tokens'
      path: '/tokens'
      fullPath: '/mcp/tokens'
      preLoaderRoute: typeof McpTokensRouteImport
      parentRoute: typeof McpRoute
    }
    '/orchestration/orchestrators': {
      id: '/orchestration/orchestrators'
      path: '/orchestrators'
      fullPath: '/orchestration/orchestrators'
      preLoaderRoute: typeof OrchestrationOrchestratorsRouteImport
      parentRoute: typeof OrchestrationRoute
    }
    '/orchestration/workers': {
      id: '/orchestration/workers'
      path: '/workers'
      fullPath: '/orchestration/workers'
      preLoaderRoute: typeof OrchestrationWorkersRouteImport
      parentRoute: typeof OrchestrationRoute
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/schedules/$id': {
      id: '/schedules/$id'
      path: '/$id'
      fullPath: '/schedules/$id'
      preLoaderRoute: typeof SchedulesIdRouteImport
      parentRoute: typeof SchedulesRoute
    }
    '/schedules/new': {
      id: '/schedules/new'
      path: '/new'
      fullPath: '/schedules/new'
      preLoaderRoute: typeof SchedulesNewRouteImport
      parentRoute: typeof SchedulesRoute
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/transfers/$id': {
      id: '/transfers/$id'
      path: '/$id'
      fullPath: '/transfers/$id'
      preLoaderRoute: typeof TransfersIdRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/transfers/new': {
      id: '/transfers/new'
      path: '/new'
      fullPath: '/transfers/new'
      preLoaderRoute: typeof TransfersNewRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/new': {
      id: '/workflows/new'
      path: '/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/_home/c/$id': {
      id: '/_home/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof HomeCIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/agents/$id/activity': {
      id: '/agents/$id/activity'
      path: '/activity'
      fullPath: '/agents/$id/activity'
      preLoaderRoute: typeof AgentsIdActivityRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/agents/$id/destinations': {
      id: '/agents/$id/destinations'
      path: '/destinations'
      fullPath: '/agents/$id/destinations'
      preLoaderRoute: typeof AgentsIdDestinationsRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/agents/$id/logs': {
      id: '/agents/$id/logs'
      path: '/logs'
      fullPath: '/agents/$id/logs'
      preLoaderRoute: typeof AgentsIdLogsRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/agents/$id/overview': {
      id: '/agents/$id/overview'
      path: '/overview'
      fullPath: '/agents/$id/overview'
      preLoaderRoute: typeof AgentsIdOverviewRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/agents/$id/rooms': {
      id: '/agents/$id/rooms'
      path: '/rooms'
      fullPath: '/agents/$id/rooms'
      preLoaderRoute: typeof AgentsIdRoomsRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/agents/$id/settings': {
      id: '/agents/$id/settings'
      path: '/settings'
      fullPath: '/agents/$id/settings'
      preLoaderRoute: typeof AgentsIdSettingsRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/agents/$id/tunnels': {
      id: '/agents/$id/tunnels'
      path: '/tunnels'
      fullPath: '/agents/$id/tunnels'
      preLoaderRoute: typeof AgentsIdTunnelsRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/mcp/tokens/new': {
      id: '/mcp/tokens/new'
      path: '/new'
      fullPath: '/mcp/tokens/new'
      preLoaderRoute: typeof McpTokensNewRouteImport
      parentRoute: typeof McpTokensRoute
    }
    '/orchestration/orchestrators/$id': {
      id: '/orchestration/orchestrators/$id'
      path: '/$id'
      fullPath: '/orchestration/orchestrators/$id'
      preLoaderRoute: typeof OrchestrationOrchestratorsIdRouteImport
      parentRoute: typeof OrchestrationOrchestratorsRoute
    }
    '/orchestration/workers/$id': {
      id: '/orchestration/workers/$id'
      path: '/$id'
      fullPath: '/orchestration/workers/$id'
      preLoaderRoute: typeof OrchestrationWorkersIdRouteImport
      parentRoute: typeof OrchestrationWorkersRoute
    }
    '/registry_/$scope/$name': {
      id: '/registry_/$scope/$name'
      path: '/registry/$scope/$name'
      fullPath: '/registry/$scope/$name'
      preLoaderRoute: typeof RegistryScopeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id/activity': {
      id: '/rooms/$id/activity'
      path: '/activity'
      fullPath: '/rooms/$id/activity'
      preLoaderRoute: typeof RoomsIdActivityRouteImport
      parentRoute: typeof RoomsIdRoute
    }
    '/rooms/$id/channels': {
      id: '/rooms/$id/channels'
      path: '/channels'
      fullPath: '/rooms/$id/channels'
      preLoaderRoute: typeof RoomsIdChannelsRouteImport
      parentRoute: typeof RoomsIdRoute
    }
    '/rooms/$id/members': {
      id: '/rooms/$id/members'
      path: '/members'
      fullPath: '/rooms/$id/members'
      preLoaderRoute: typeof RoomsIdMembersRouteImport
      parentRoute: typeof RoomsIdRoute
    }
    '/rooms/$id/settings': {
      id: '/rooms/$id/settings'
      path: '/settings'
      fullPath: '/rooms/$id/settings'
      preLoaderRoute: typeof RoomsIdSettingsRouteImport
      parentRoute: typeof RoomsIdRoute
    }
    '/rooms/$id/transfers': {
      id: '/rooms/$id/transfers'
      path: '/transfers'
      fullPath: '/rooms/$id/transfers'
      preLoaderRoute: typeof RoomsIdTransfersRouteImport
      parentRoute: typeof RoomsIdRoute
    }
    '/schedules/$id/edit': {
      id: '/schedules/$id/edit'
      path: '/edit'
      fullPath: '/schedules/$id/edit'
      preLoaderRoute: typeof SchedulesIdEditRouteImport
      parentRoute: typeof SchedulesIdRoute
    }
    '/workflows/$id/editor': {
      id: '/workflows/$id/editor'
      path: '/editor'
      fullPath: '/workflows/$id/editor'
      preLoaderRoute: typeof WorkflowsIdEditorRouteImport
      parentRoute: typeof WorkflowsIdRoute
    }
    '/workflows/$id/overview': {
      id: '/workflows/$id/overview'
      path: '/overview'
      fullPath: '/workflows/$id/overview'
      preLoaderRoute: typeof WorkflowsIdOverviewRouteImport
      parentRoute: typeof WorkflowsIdRoute
    }
    '/workflows/$id/runs': {
      id: '/workflows/$id/runs'
      path: '/runs'
      fullPath: '/workflows/$id/runs'
      preLoaderRoute: typeof WorkflowsIdRunsRouteImport
      parentRoute: typeof WorkflowsIdRoute
    }
    '/workflows/$id/settings': {
      id: '/workflows/$id/settings'
      path: '/settings'
      fullPath: '/workflows/$id/settings'
      preLoaderRoute: typeof WorkflowsIdSettingsRouteImport
      parentRoute: typeof WorkflowsIdRoute
    }
    '/workflows/runs/$id': {
      id: '/workflows/runs/$id'
      path: '/runs/$id'
      fullPath: '/workflows/runs/$id'
      preLoaderRoute: typeof WorkflowsRunsIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/rooms/$id/channels/$channelId': {
      id: '/rooms/$id/channels/$channelId'
      path: '/$channelId'
      fullPath: '/rooms/$id/channels/$channelId'
      preLoaderRoute: typeof RoomsIdChannelsChannelIdRouteImport
      parentRoute: typeof RoomsIdChannelsRoute
    }
    '/workflows/$id/runs/$runId': {
      id: '/workflows/$id/runs/$runId'
      path: '/$runId'
      fullPath: '/workflows/$id/runs/$runId'
      preLoaderRoute: typeof WorkflowsIdRunsRunIdRouteImport
      parentRoute: typeof WorkflowsIdRunsRoute
    }
    '/rooms/$id/channels/$channelId/details': {
      id: '/rooms/$id/channels/$channelId/details'
      path: '/details'
      fullPath: '/rooms/$id/channels/$channelId/details'
      preLoaderRoute: typeof RoomsIdChannelsChannelIdDetailsRouteImport
      parentRoute: typeof RoomsIdChannelsChannelIdRoute
    }
  }
}

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeCIdRoute: typeof HomeCIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeCIdRoute: HomeCIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface AgentsIdRouteChildren {
  AgentsIdActivityRoute: typeof AgentsIdActivityRoute
  AgentsIdDestinationsRoute: typeof AgentsIdDestinationsRoute
  AgentsIdLogsRoute: typeof AgentsIdLogsRoute
  AgentsIdOverviewRoute: typeof AgentsIdOverviewRoute
  AgentsIdRoomsRoute: typeof AgentsIdRoomsRoute
  AgentsIdSettingsRoute: typeof AgentsIdSettingsRoute
  AgentsIdTunnelsRoute: typeof AgentsIdTunnelsRoute
}

const AgentsIdRouteChildren: AgentsIdRouteChildren = {
  AgentsIdActivityRoute: AgentsIdActivityRoute,
  AgentsIdDestinationsRoute: AgentsIdDestinationsRoute,
  AgentsIdLogsRoute: AgentsIdLogsRoute,
  AgentsIdOverviewRoute: AgentsIdOverviewRoute,
  AgentsIdRoomsRoute: AgentsIdRoomsRoute,
  AgentsIdSettingsRoute: AgentsIdSettingsRoute,
  AgentsIdTunnelsRoute: AgentsIdTunnelsRoute,
}

const AgentsIdRouteWithChildren = AgentsIdRoute._addFileChildren(
  AgentsIdRouteChildren,
)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface CredentialsRouteChildren {
  CredentialsNewRoute: typeof CredentialsNewRoute
}

const CredentialsRouteChildren: CredentialsRouteChildren = {
  CredentialsNewRoute: CredentialsNewRoute,
}

const CredentialsRouteWithChildren = CredentialsRoute._addFileChildren(
  CredentialsRouteChildren,
)

interface McpTokensRouteChildren {
  McpTokensNewRoute: typeof McpTokensNewRoute
}

const McpTokensRouteChildren: McpTokensRouteChildren = {
  McpTokensNewRoute: McpTokensNewRoute,
}

const McpTokensRouteWithChildren = McpTokensRoute._addFileChildren(
  McpTokensRouteChildren,
)

interface McpRouteChildren {
  McpActivityRoute: typeof McpActivityRoute
  McpCapabilitiesRoute: typeof McpCapabilitiesRoute
  McpConnectionRoute: typeof McpConnectionRoute
  McpTokensRoute: typeof McpTokensRouteWithChildren
}

const McpRouteChildren: McpRouteChildren = {
  McpActivityRoute: McpActivityRoute,
  McpCapabilitiesRoute: McpCapabilitiesRoute,
  McpConnectionRoute: McpConnectionRoute,
  McpTokensRoute: McpTokensRouteWithChildren,
}

const McpRouteWithChildren = McpRoute._addFileChildren(McpRouteChildren)

interface OrchestrationOrchestratorsRouteChildren {
  OrchestrationOrchestratorsIdRoute: typeof OrchestrationOrchestratorsIdRoute
}

const OrchestrationOrchestratorsRouteChildren: OrchestrationOrchestratorsRouteChildren =
  {
    OrchestrationOrchestratorsIdRoute: OrchestrationOrchestratorsIdRoute,
  }

const OrchestrationOrchestratorsRouteWithChildren =
  OrchestrationOrchestratorsRoute._addFileChildren(
    OrchestrationOrchestratorsRouteChildren,
  )

interface OrchestrationWorkersRouteChildren {
  OrchestrationWorkersIdRoute: typeof OrchestrationWorkersIdRoute
}

const OrchestrationWorkersRouteChildren: OrchestrationWorkersRouteChildren = {
  OrchestrationWorkersIdRoute: OrchestrationWorkersIdRoute,
}

const OrchestrationWorkersRouteWithChildren =
  OrchestrationWorkersRoute._addFileChildren(OrchestrationWorkersRouteChildren)

interface OrchestrationRouteChildren {
  OrchestrationOrchestratorsRoute: typeof OrchestrationOrchestratorsRouteWithChildren
  OrchestrationWorkersRoute: typeof OrchestrationWorkersRouteWithChildren
}

const OrchestrationRouteChildren: OrchestrationRouteChildren = {
  OrchestrationOrchestratorsRoute: OrchestrationOrchestratorsRouteWithChildren,
  OrchestrationWorkersRoute: OrchestrationWorkersRouteWithChildren,
}

const OrchestrationRouteWithChildren = OrchestrationRoute._addFileChildren(
  OrchestrationRouteChildren,
)

interface RoomsIdChannelsChannelIdRouteChildren {
  RoomsIdChannelsChannelIdDetailsRoute: typeof RoomsIdChannelsChannelIdDetailsRoute
}

const RoomsIdChannelsChannelIdRouteChildren: RoomsIdChannelsChannelIdRouteChildren =
  {
    RoomsIdChannelsChannelIdDetailsRoute: RoomsIdChannelsChannelIdDetailsRoute,
  }

const RoomsIdChannelsChannelIdRouteWithChildren =
  RoomsIdChannelsChannelIdRoute._addFileChildren(
    RoomsIdChannelsChannelIdRouteChildren,
  )

interface RoomsIdChannelsRouteChildren {
  RoomsIdChannelsChannelIdRoute: typeof RoomsIdChannelsChannelIdRouteWithChildren
}

const RoomsIdChannelsRouteChildren: RoomsIdChannelsRouteChildren = {
  RoomsIdChannelsChannelIdRoute: RoomsIdChannelsChannelIdRouteWithChildren,
}

const RoomsIdChannelsRouteWithChildren = RoomsIdChannelsRoute._addFileChildren(
  RoomsIdChannelsRouteChildren,
)

interface RoomsIdRouteChildren {
  RoomsIdActivityRoute: typeof RoomsIdActivityRoute
  RoomsIdChannelsRoute: typeof RoomsIdChannelsRouteWithChildren
  RoomsIdMembersRoute: typeof RoomsIdMembersRoute
  RoomsIdSettingsRoute: typeof RoomsIdSettingsRoute
  RoomsIdTransfersRoute: typeof RoomsIdTransfersRoute
}

const RoomsIdRouteChildren: RoomsIdRouteChildren = {
  RoomsIdActivityRoute: RoomsIdActivityRoute,
  RoomsIdChannelsRoute: RoomsIdChannelsRouteWithChildren,
  RoomsIdMembersRoute: RoomsIdMembersRoute,
  RoomsIdSettingsRoute: RoomsIdSettingsRoute,
  RoomsIdTransfersRoute: RoomsIdTransfersRoute,
}

const RoomsIdRouteWithChildren =
  RoomsIdRoute._addFileChildren(RoomsIdRouteChildren)

interface RoomsRouteChildren {
  RoomsIdRoute: typeof RoomsIdRouteWithChildren
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsIdRoute: RoomsIdRouteWithChildren,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface RunsRouteChildren {
  RunsIdRoute: typeof RunsIdRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsIdRoute: RunsIdRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

interface SchedulesIdRouteChildren {
  SchedulesIdEditRoute: typeof SchedulesIdEditRoute
}

const SchedulesIdRouteChildren: SchedulesIdRouteChildren = {
  SchedulesIdEditRoute: SchedulesIdEditRoute,
}

const SchedulesIdRouteWithChildren = SchedulesIdRoute._addFileChildren(
  SchedulesIdRouteChildren,
)

interface SchedulesRouteChildren {
  SchedulesIdRoute: typeof SchedulesIdRouteWithChildren
  SchedulesNewRoute: typeof SchedulesNewRoute
}

const SchedulesRouteChildren: SchedulesRouteChildren = {
  SchedulesIdRoute: SchedulesIdRouteWithChildren,
  SchedulesNewRoute: SchedulesNewRoute,
}

const SchedulesRouteWithChildren = SchedulesRoute._addFileChildren(
  SchedulesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccessRoute: typeof SettingsAccessRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccessRoute: SettingsAccessRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TransfersRouteChildren {
  TransfersIdRoute: typeof TransfersIdRoute
  TransfersNewRoute: typeof TransfersNewRoute
}

const TransfersRouteChildren: TransfersRouteChildren = {
  TransfersIdRoute: TransfersIdRoute,
  TransfersNewRoute: TransfersNewRoute,
}

const TransfersRouteWithChildren = TransfersRoute._addFileChildren(
  TransfersRouteChildren,
)

interface WorkflowsIdRunsRouteChildren {
  WorkflowsIdRunsRunIdRoute: typeof WorkflowsIdRunsRunIdRoute
}

const WorkflowsIdRunsRouteChildren: WorkflowsIdRunsRouteChildren = {
  WorkflowsIdRunsRunIdRoute: WorkflowsIdRunsRunIdRoute,
}

const WorkflowsIdRunsRouteWithChildren = WorkflowsIdRunsRoute._addFileChildren(
  WorkflowsIdRunsRouteChildren,
)

interface WorkflowsIdRouteChildren {
  WorkflowsIdEditorRoute: typeof WorkflowsIdEditorRoute
  WorkflowsIdOverviewRoute: typeof WorkflowsIdOverviewRoute
  WorkflowsIdRunsRoute: typeof WorkflowsIdRunsRouteWithChildren
  WorkflowsIdSettingsRoute: typeof WorkflowsIdSettingsRoute
}

const WorkflowsIdRouteChildren: WorkflowsIdRouteChildren = {
  WorkflowsIdEditorRoute: WorkflowsIdEditorRoute,
  WorkflowsIdOverviewRoute: WorkflowsIdOverviewRoute,
  WorkflowsIdRunsRoute: WorkflowsIdRunsRouteWithChildren,
  WorkflowsIdSettingsRoute: WorkflowsIdSettingsRoute,
}

const WorkflowsIdRouteWithChildren = WorkflowsIdRoute._addFileChildren(
  WorkflowsIdRouteChildren,
)

interface WorkflowsRouteChildren {
  WorkflowsIdRoute: typeof WorkflowsIdRouteWithChildren
  WorkflowsNewRoute: typeof WorkflowsNewRoute
  WorkflowsRunsIdRoute: typeof WorkflowsRunsIdRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsIdRoute: WorkflowsIdRouteWithChildren,
  WorkflowsNewRoute: WorkflowsNewRoute,
  WorkflowsRunsIdRoute: WorkflowsRunsIdRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  AuthRoute: AuthRoute,
  CredentialsRoute: CredentialsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeadLetterRoute: DeadLetterRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRouteWithChildren,
  NewRoute: NewRoute,
  OrchestrationRoute: OrchestrationRouteWithChildren,
  QueueRoute: QueueRoute,
  RegistryRoute: RegistryRoute,
  RoomsRoute: RoomsRouteWithChildren,
  RunsRoute: RunsRouteWithChildren,
  SchedulesRoute: SchedulesRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TransfersRoute: TransfersRouteWithChildren,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  RegistryScopeNameRoute: RegistryScopeNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
