export const mcpToolNames = [
  "beam.list_rooms",
  "beam.list_room_storage_members",
  "beam.attach_room_storage_member",
  "beam.update_room_storage_member",
  "beam.remove_room_storage_member",
  "beam.create_room_workflow",
  "beam.create_workflow",
  "beam.get_workflow",
  "beam.update_workflow_graph",
  "beam.run_workflow",
  "beam.retry_workflow_run",
  "beam.get_workflow_run",
  "beam.cancel_workflow_run",
  "beam.list_api_keys",
  "beam.list_credentials",
  "beam.create_transfer",
  "beam.run_transfer_now",
  "beam.schedule_transfer",
  "beam.cancel_run",
  "beam.get_run_status",
  "beam.get_transfer_status",
  "beam.list_recent_runs",
] as const;
