-- One Core transfer may deliver the same artifact to several members. Keep
-- nullable historical storage locations while making each member copy unique.
ALTER TABLE execution.workflow_artifact_locations
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE execution.workflow_artifact_locations SET id=DEFAULT WHERE id IS NULL;
ALTER TABLE execution.workflow_artifact_locations
  DROP CONSTRAINT IF EXISTS workflow_artifact_locations_pkey;
ALTER TABLE execution.workflow_artifact_locations
  ADD CONSTRAINT workflow_artifact_locations_pkey PRIMARY KEY(id);
CREATE UNIQUE INDEX IF NOT EXISTS workflow_artifact_locations_member_identity
  ON execution.workflow_artifact_locations
  (manifest_id,artifact_id,kind,locator,COALESCE(member_id,''));
